# Generated by Django 5.2.7 on 2025-11-25 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_perfil_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAccesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(choices=[('faltante', 'Faltante'), ('roto', 'Roto/Dañado'), ('extraviado', 'Extraviado'), ('otro', 'Otro')], default='faltante', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del problema')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas_confirmacion', models.TextField(blank=True, help_text='Notas del admin al confirmar/rechazar')),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='api.accesorios')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_confirmados', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Accesorio',
                'verbose_name_plural': 'Reportes de Accesorios',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
