# Generated by Django 5.2.7 on 2025-11-27 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reporteaccesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo'), django.core.validators.MaxValueValidator(300, message='El stock no puede superar las 300 unidades')]),
        ),
    ]
