# Generated by Django 5.2.7 on 2025-10-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proveedor_accesorios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorios',
            old_name='sotck',
            new_name='stock',
        ),
    ]
