# Generated by Django 5.2.6 on 2025-10-28 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_sotck_accesorios_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='deactivate_at',
            new_name='deactivated_at',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 28, 6, 59, 28, 975284, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
