# Generated by Django 5.2.7 on 2025-10-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_compra_itemcompra'),
        ('api', '0007_rename_deactivate_at_perfil_deactivated_at_and_more'),
    ]

    operations = [
    ]
