# Generated by Django 5.2.7 on 2025-10-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20251029_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='deactivated_at',
            new_name='deactivate_at',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_creacion',
        ),
    ]
