# Generated by Django 5.2.7 on 2025-10-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reportefaltante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteFaltante',
        ),
    ]
