# Generated by Django 5.2.7 on 2025-10-31 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(verbose_name='Fecha/Hora de Inicio')),
                ('hora_fin', models.DateTimeField(verbose_name='Fecha/Hora de Fin')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado por Socio'), ('FINALIZADO', 'Finalizado (Asistido)')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hora_inicio'],
            },
        ),
    ]
