# Generated by Django 5.2.7 on 2025-11-17 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Cupo Disponible'), ('RESERVADO', 'Reservado - Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado/Liberado'), ('FINALIZADO', 'Finalizado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reservados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno/Cupo de 1 hora',
                'verbose_name_plural': 'Turnos/Cupos',
                'ordering': ['hora_inicio'],
                'indexes': [models.Index(fields=['hora_inicio', 'estado'], name='turnos_turn_hora_in_52ab73_idx')],
            },
        ),
    ]
