# Generated by Django 5.2.6 on 2025-11-16 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['hora_inicio', 'estado'], name='turnos_turn_hora_in_52ab73_idx'),
        ),
    ]
