# Generated by Django 5.2.6 on 2025-11-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Cupo Disponible'), ('RESERVADO', 'Reservado - Pendiente de Confirmación'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado/Liberado'), ('FINALIZADO', 'Finalizado'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20),
        ),
    ]
