# Generated by Django 5.2.7 on 2025-11-17 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_popular', models.BooleanField(default=False)),
                ('caracteristicas', models.TextField(blank=True, help_text='Características separadas por coma. Ej: Acceso sala de musculación, Vestuarios y duchas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'cuotas_planes',
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='CuotaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(max_length=100)),
                ('plan_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('tarjeta_ultimos_4', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio', models.ForeignKey(limit_choices_to={'groups__name': 'socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_mensuales', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuotas_mensuales.plan')),
            ],
            options={
                'verbose_name': 'Cuota Mensual',
                'verbose_name_plural': 'Cuotas Mensuales',
                'db_table': 'cuotas_mensuales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='tarjeta', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('movimiento_caja_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuotas_mensuales.cuotamensual')),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'db_table': 'cuotas_historial_pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='cuotamensual',
            index=models.Index(fields=['socio', 'estado'], name='cuotas_mens_socio_i_4af39d_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotamensual',
            index=models.Index(fields=['fecha_vencimiento'], name='cuotas_mens_fecha_v_08f12e_idx'),
        ),
    ]
