# Generated by Django 5.2.6 on 2025-11-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotamensual',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida')], default='activa', max_length=20),
        ),
    ]
