# Generated by Django 5.2.7 on 2025-11-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas_mensuales', '0002_alter_cuotamensual_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cantidad_limite',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad de turnos permitidos por período (0 para ilimitado)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tipo_limite',
            field=models.CharField(choices=[('semanal', 'Semanal (X veces por semana)'), ('diario', 'Diario (X veces por día)'), ('libre', 'Pase Libre (Sin límite)')], default='semanal', help_text='Define cómo se cuenta el límite de turnos', max_length=20),
        ),
    ]
