# Generated by Django 5.2.7 on 2025-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas_mensuales', '0003_plan_cantidad_limite_plan_tipo_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotamensual',
            name='clases_restantes',
            field=models.PositiveIntegerField(default=12, help_text='Clases disponibles en el mes actual'),
        ),
        migrations.AddField(
            model_name='cuotamensual',
            name='clases_totales',
            field=models.PositiveIntegerField(default=12, help_text='Total de clases incluidas en el plan'),
        ),
    ]
