# Generated by Django 5.2.7 on 2025-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas_mensuales', '0004_cuotamensual_clases_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotamensual',
            name='clases_restantes',
            field=models.PositiveIntegerField(default=0, help_text='Clases disponibles en el mes actual'),
        ),
        migrations.AlterField(
            model_name='cuotamensual',
            name='clases_totales',
            field=models.PositiveIntegerField(default=0, help_text='Total de clases incluidas en el plan'),
        ),
    ]
