# Generated by Django 5.2.7 on 2025-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='closing_system_amount',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='difference_amount',
        ),
        migrations.AddField(
            model_name='movimientodecaja',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
