# Generated by Django 5.2.6 on 2025-11-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodecaja',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=50),
        ),
    ]
