# Generated by Django 5.2.7 on 2025-10-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_proveedor_email_proveedor_fecha_actualizacion_and_more'),
        ('movimiento_caja', '0002_remove_caja_closing_system_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodecaja',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='api.compra', verbose_name='Compra relacionada'),
        ),
    ]
