# Generated by Django 5.2.7 on 2025-11-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0003_movimientodecaja_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='notas',
        ),
    ]
