# Generated by Django 5.2.7 on 2025-11-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_caja', '0004_remove_caja_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
